### PR TITLE
Typescript with *.d.ts files

### PR DESCRIPTION
**Pull request by antonk52**
I've noticed this package is missing typescript types. I was able to cover most of the cases and think this can be a good addition to the npm package.

You can the addition in action in the [playground](https://www.typescriptlang.org/play?ts=4.1.3#code/PQKhCgAIUheeGKclq3o52UYBUCeADgKYDOOcWV1NtCOw4AJsQMYA2AhgE7GQBmAVwB2rAC4BLAPbDIncdOEAKAJQAuSAG8xRYhtJjuE4QHMAvgG5mbLrwEiFMuY+EAeXAD4lPExtzqtHRJ9Q2MTC0hCTnx2KU4mP0trDh4+IVFJJ3lMt1wAGkgAWS8fPwKAW2IxTg1CgO1dEKNTCKiYuITIXAjK6tqklhS7dJdnHO9uEwB+DU5hfAqqzhm5efqgvUgDZvDI6Nj4lbn8HqWj+aTk2zSHHMhibm4pbncSyb91xq3Qlr32+LK90ezw0hkExAGNlS9gyiiBTxe+SKb18XUWfSKn2C3x2rX2HT8pwxhQKDwRoO44MhQxusKcZOeE2ms3m6OWLPwWM22zCBTaByY5wWkF67NWwoZ3ApVKsV2hIzuxHKhB0qg0DWxPNMlw2kAAggAjbbZPUuUhwSAAJTYzyYri1JgKSgAdK6fKQOSo4B5xR5wLqACQAUQAHtlXhbcJAAGRaADaAGtiPhIMYcWEALorXCJ5NSfhdDOQAA+kGExAAbg8ksQQ4RnmJILrQ4YTWaAGJPcoACTmTHYD1Irm79xDYmIwiY5t7k4H3CHxwKhuN4lNOVIHh9sC0UEge7jAGlU7Ik-h85BuxmNNaAI6CCS8O3djyHou18eT80ut2TD2QOOLse-APPqLgFK6zrHHGGYZl6sA+sckBTKBdwaOWVbcFYZi5meBaXlYtb1twjbNmO3DZAAytU46dlIPZ9nOQ4ju+E5TheDGDq4gHLq2q5mpuFqaLu+5Hmmp7npe17EHeD7EE+L4Hm+Y6sV+EHuhocbGMB3CQFRnDjuBbrzNBsHeuKSG6dRfBoZWDxYThEkZrKcrDLccKsLw+nEGuihDlGLGfvqRq8WIPkyBuSjCXI7xouA9RRYex6QOJBa4FekAAAo8JwvScTmik+gFbGacI2mZQUWkgYUGZRXue7IUyGgZWytRwT6GqbAeeL-J0GVEjURRmLVdVNdluXzu4r6FcpgUlWVGU1XVS0WY1mVtYEXxdX8ApNUNy0jZAqhmR1GgHkklyEQ2Ta6Oxs6cRRS6jh+bE8eRfHrluO5LYlYl5gWepZhoSgGF5GgPWMihSWIgjcMIBAkK4epTetwZhuIrgUX6lzAMAkAsOUUiQDIA7+jd1pMIIrAPBjFrcbTrJWhamMWsDVlgwU2SQ-q62WlYgzXDCowABYcWFwh+U9Km3f2nHccFb2hfxKIfFJFNUy8LYK3pNFdjOMsTZ4BSa22660fRd0G5u4DgJdxHXSQkAAJLlJU3B64xNNFeaIgJsIUgAO7CI9XtBSuisfYJCWiSef36oDh0g+O7MQzIUMw3DuiI8jZkVlIEhMFh1v8-KblOCLd3O67YsSyHlcPO7ssM8cm6rf4quU9TxviNrxBmw3ltG2RJu+X3HED5Auf5364CgBA0CUHQi9L0vFDVxQy8b5vWAMNbtuNqw4WNgAqhlAAieq4EGFoAOQAALCDlZBRFTwAn+fl-XzbdZXQf4vH2fF8gwAH12xHwADLtkdmAsBQZT433vo-Ugz9iCvwAZfEB4DIHQNgZ-PekBf4GEgG-QBIC9RQNgfAh+lQkHyBQcQ9B7YyEwNPp-UmDsgzCEkDoR2TBBL5zQoIcoBpqzWwIY2Tm4ULQeWIF5auSghJLVnrVGAJ0iFoKDHtJaIBGDfXoUGdKSoVQLCiko5aKiNgaD0RgiBUDmF8nxACSAHCuH4B4dBTRdVtEJSsaAmx2DT7pSUCGDQziJDcKYNBdaEjlAhhUHkExYBlEbWxD4phsD7E9RCZwsJrimAtS0KQfAohpQQg8XuLxuj1GkPIQEoGwSnHZPCfkzQhTilNkpBCKJLgglsjieAMwKhd7fztmIr6dU4x6PSoIQgTAvLxMqe-YBvisHMKmTMry7ZBDsH4BIdgA48neKqYwmpazZk0U4LsuS8SzC0zNEMoiJEbrVwtBsc80TyAz0SfPLePzfmIAoOTDu8515-NBZvHebC+A90jktROgg-zXyYDIYg18SyQGviQScYRUWlmvpKHF6L+AXP2dfKwS1PJMHwBoA0UgpADjmGSuqZyxShPCdBQuX8Hn2yhTlQgA5+7mm3AKjGVklz8VlHg0ZvATBbJ4A3Z525y4yzkQouqpitGQAAHKE3LHJJshN6zGBIkLKFVkug3TTD4QRE4xCkHmRqsJkB-ZSC2bw4RchBBiCkAAWkqo8PVp9iDEEIE7F2nrOAGgHOah254e7KJ0eMyZIQvJmXkcNPcEFE7EHtftOFCLMVMGxTmyAAz4kJLnhq3AJqtg2knNFGVlROGHWiV6f2uz2ByHYKQQmIsqxNmrUYEwQtHkkCSaonxmDbHpO2gSBpLi3EZjKdABN+4J1+NWUDLNBRND8g6AM1Nqr9qZtFemvG+kBq7viMW2F1F4UaERci6+xbS3WwWSQ45G6E6ipTsIdaab9oZtdFu09FKqU-udKKZ0rTWDXrqnm+9RLLlMCfaenGXQADyp90MaEADLkkBb62u9YRNgYgiPAilFsIWLr2C8PIhIUgfA5jwmeAIFjPs-aB0iE8EgxEUw4dPexgOwh2wSGIDRkpz6+k3M4NOMeQ4e5io+oMtDAA9FTZYpDjn7XwQi7AJCsEdawGTjYACEZn+n3KuiwIlWzGxKoHHXbgcj-2JvUelLNx1T1Zqg7ewV6KC3YqimYMtb6GGTv8YErdWhL1MH3fBMZuarLOmZRaGLXmkt5pvki8sn8lrBdfa5xZ1TP0efi4e5a3nMvbmvohklqHcYEdIERusJGyMIkgIAUHJIAAHV0OWgPBREznX0teWdIJwOImxO8O3GCYgjK9z5ek+aRzwqFMoV8h4FQKgrCqfU37LTYhq26f04Z4zkAzMmetqYmAYLbsr3nvDMgHkJAqlTKQUg4IQV3e+1QCF12uhC3o6OXlUaTXsEIOaL1qY9nwtbAd6t9GPt8H9kLFMGxSDPde0Z4Q+3IDurBAYOSFAWMo5TI6iQJg-a8HNPEQtOROAdsINx80aZHxAvIMuzlV0FRwn4LS1aDp6gDQdAUA01LaX0uEDc8rUqyCCQGj4UXEmnZANIFR11QD9tAOEUAk1vANAAEYABMABmS45Kqjp0gNTiIaGRaGD1f7GTePniyD18QCzXO7Y86cAaHgAufgmACKjcMmhheB6Vy7ulMipftSirLvzYfZiTEj7NgojtVfq5o5rzT2viC64eJsY3ZvZSKIa4R4j4g2sgk65AKjzxojDYt9DWG1uyAcrwT72QfuABeAedjB9DKH8POxI80uj3MMwceloJ-l8nx0ePlcZ7V9RpgOexB54L-r9pMoCt7jQ3h9HmPGyFt4bjozYhWBC208xnSpBjBUxv0zqQIaKwM-BG9om5YiYFkr+OXhb+7A4I5o-GzeVuNu-SQAA)

There are a couple of things to note:
- There is a an edge case(noted in the playground) I was not able to cover due to structural type system in typescript or me being inexperienced in it.
- There are not types the redux-observable api, since the current types are for an older rxjs api and in my experience the package users provide their own `Epic` type.
- There are not types the `weak.js` api, since it was not documented.

I think this PR should improve the package adoption for typescript users. Hope this helps.

### CODE REVIEW

**Comment by lttb** [comment]
Hi @antonk52, thank you a lot for your effort, I'll try to check it asap.

Would you mind adding some tests, please?

**Comment by antonk52** [comment]
Great idea! I've added a few test cases and made sure the positive cases work as expected and some of the negative ones too. I am sure there are a few things I haven't tested for but cannot come up with any missing cases atm. If you can think of any, please let me know

**Review by lttb — APPROVED** [review]

**Comment by lttb** [comment]
Looks fantastic, thank you! Feel free to let me know when you'll be ready to release

**Comment by antonk52** [comment]
I've discovered a couple of issues with the current types, to be more specific:

- error action creator types do not currently have `errror: true`
- meta arguments do not always end up in the final action type
- the optional second argument for `handleActions` should have the same type as T

I'm going to fix the types and tests to cover these errors. Once it's done the types should be ready to cut a new release

**Comment by antonk52** [comment]
I've fixed the errors and added a few more test cases for the action and handleActions types. From what I can see this should be alright now

**Pull request merged**
